use colored::*;

#[derive(Debug, Clone)]
pub struct RuleExplanation {
    pub id: &'static str,
    pub name: &'static str,
    pub severity: &'static str,
    pub tag: &'static str,
    pub summary: &'static str,
    pub rationale: &'static str,
    pub bad_example: &'static str,
    pub good_example: &'static str,
    pub remediation: &'static str,
}

pub static EXPLANATIONS: &[RuleExplanation] = &[
    RuleExplanation {
        id: "DOC-VIBE-DISCLAIMER",
        name: "Standardized StenioSentinel Governance Disclaimer Missing or Inconsistent",
        severity: "ERROR",
        tag: "doc",
        summary: "Enforces the standardized human-AI governance disclaimer ('Human-in-the-Loop Agentic Engineering & Deterministic Governance') and blocks legacy vibe-coding badges in public repositories.",
        rationale: "Ensures transparency regarding agentic engineering governance and human authorship across open-source and public projects led by Carlos Eduardo Rodrigues, positioning StenioSentinel as the deterministic guardian of integrity.",
        bad_example: "> 🔮 **Yes... This is a Vibe Coded project**\n# Or README missing any governance disclaimer.",
        good_example: "<div align=\"center\">\n\n### 🛡️ Human-in-the-Loop Agentic Engineering & Deterministic Governance\n\n> **Architected by an Anthropologist, Built with Autonomous AI Agents, Governed by Deterministic Code.**\n> \n> This project was developed through rigorous human-AI pair programming led by **Carlos Eduardo Rodrigues** ([@ceduardorodrig](https://github.com/ceduardorodrig)) — an anthropologist and product architect using autonomous coding agents under strict, sub-millisecond static governance.\n>\n> Every commit, driver, and system architecture is continuously audited and enforced by 🤖 **[StenioSentinel](https://github.com/ceduardorodrig/STENIO-SENTINEL)** (our native Rust quality gate) with zero tolerance for hallucinated tests, blind merges, or bypassed checks.\n\n</div>",
        remediation: "Insert the standardized centered HTML block at the bottom of README.md.",
    },
    RuleExplanation {
        id: "SEC-SUDO",
        name: "Privileged Sudo Execution in Script",
        severity: "WARN",
        tag: "sec",
        summary: "Flags ANY use of sudo in scripts. Not an error accusation: it is a mandatory review point to guarantee privilege is intentional, minimal, and non-interactive.",
        rationale: "The rule was deliberately EXPANDED on 2026-09-16: previously it matched only 6 commands, creating a leaky whitelist where unlisted commands escaped silently. Today it matches '\\bsudo\\s+' (any command), because the risk lies in the PRIVILEGE PATTERN, not the command name. There is no automated bypass: shrinking the regex reopens the gap, which is why this signature is pinned in Guardian (anti-tampering). In headless server fleets (ybyra/ybytu/kuaray/kavure) and containers, pkexec fails; on KDE desktops it triggers repetitive dialogs. The professional approach is: 1) NOPASSWD in sudoers for AUTOMATED TASKS, scoped minimally; 2) credentials via .env or SOPS/Age vault; 3) pkexec reserved for interactive manual interventions.",
        bad_example: "# Unchecked privilege:\nsudo apt install pkg1\nsudo rm -rf /var/lib/docker\n\n# Password piped via stdin:\necho 'secret' | sudo -S systemctl restart nginx\n\n# pkexec in automation (fails on headless):\npkexec systemctl restart nginx",
        good_example: "# REVIEW — rule asks for review, not total sudo elimination:\n\n# 1) Privilege is intentional, scope minimal, NOPASSWD in sudoers:\nsudo systemctl restart nginx        # reviewed\nsudo install -m 0755 bin /usr/local/bin/tool\n\n# 2) Secrets never come via pipe/stdin — load from vault:\nDATABASE_URL=$(sops -d --extract '[\"DATABASE_URL\"]' secrets.enc.env)\n\n# 3) pkexec reserved for manual desktop intervention.",
        remediation: "Treat each finding as a REVIEW point: (a) is privilege strictly necessary? (b) is scope minimal? (c) is password piped via stdin (remove — use vault)? (d) is pkexec used in automation (switch to sudoers)? There is NO suppression via stenio-ignore: SEC-* is inviolable by design. DO NOT narrow the regex: broad coverage is deliberate and pinned in Guardian.",
    },
    RuleExplanation {
        id: "RUST-NO-UNWRAP",
        name: "Use of unwrap() or expect() in Production Code",
        severity: "ERROR",
        tag: "rust",
        summary: "Strictly prohibits .unwrap() and .expect() in production Rust code.",
        rationale: "Smaller models and rushed developers frequently use .unwrap() or attempt to game the check by swapping for .expect() to bypass compiler errors. In concurrent web servers (Axum/Tokio), both .unwrap() and .expect() cause immediate thread or worker panics, crashing requests for all users.",
        bad_example: "let user = find_user(id).unwrap();\nlet config = parse_config().expect(\"Config failure\"); // PROHIBITED: expect panics!",
        good_example: "let user = find_user(id).ok_or_else(|| AppError::NotFound)?;\nlet config = parse_config().unwrap_or_default();\n// Or with pattern matching:\nlet user = match find_user(id) {\n    Some(u) => u,\n    None => return Err(AppError::NotFound),\n};",
        remediation: "Replace with '?' (try operator), pattern matching ('match'/'if let'), or safe fallback methods (.unwrap_or_default(), .unwrap_or_else()). Swapping unwrap for expect is strictly forbidden.",
    },
    RuleExplanation {
        id: "ARCH-NO-PYTHON",
        name: "Prohibited Python File",
        severity: "ERROR",
        tag: "arch",
        summary: "Prohibits .py files in the Sumænimá ecosystem (ADR-036).",
        rationale: "The Sumænimá ecosystem migrated 100% to compiled native Rust (Axum, Tokio, SQLx, GGML Q8_0). Maintaining or reintroducing Python scripts creates stack duplicity, reintroduces sluggish dependencies (PyTorch, CTranslate2), and fractures the single-binary architecture.",
        bad_example: "app/server/run_transcription.py\nscripts/worker.py",
        good_example: "app/server/src/transcription.rs\napp/server/src/bin/worker.rs",
        remediation: "Rewrite functionality in native Rust inside app/server/src/ or use existing compiled binaries.",
    },
    RuleExplanation {
        id: "ARCH-RUST-TOOLS",
        name: "Legacy GNU CLI Tools Usage in Shell Scripts",
        severity: "WARN",
        tag: "arch",
        summary: "Enforces modern tools written in native Rust instead of legacy GNU utilities.",
        rationale: "Per the mandatory terminal preferences in AGENTS.md, Rust utilities are orders of magnitude faster, have ergonomic syntax, and respect .gitignore automatically.",
        bad_example: "grep -r \"foo\" .\nfind . -name \"*.rs\"\ndu -sh *\ncat file.txt",
        good_example: "rg \"foo\"\nfd -e rs\ndust\nbat --paging=never file.txt",
        remediation: "Replace grep->rg, find->fd, du->dust, cat->bat, ls->eza, sed->sd, curl->xh.",
    },
    RuleExplanation {
        id: "ARCH-RUST-CMD-LEGACY",
        name: "Legacy GNU Tool Invoked in Rust Source",
        severity: "WARN",
        tag: "arch",
        summary: "Prohibits Command::new() calling legacy GNU utilities.",
        rationale: "Rust source code must not depend on external GNU subprocesses (curl, grep, find, df). Invoking external tools introduces fork/exec overhead, depends on host-installed packages, and violates standard library sovereignty.",
        bad_example: "Command::new(\"curl\").args([\"-s\", url]).output()\nCommand::new(\"grep\").args([\"-r\", pat]).output()",
        good_example: "let resp = reqwest::get(url).await?;\n// Or using regex crate:\nlet re = Regex::new(pat)?;",
        remediation: "Replace invocation with a native Rust crate (reqwest/xh for HTTP, regex for search, walkdir for files, statvfs/nix for disk space).",
    },
    RuleExplanation {
        id: "RUST-ASYNC-SLEEP",
        name: "std::thread::sleep in Asynchronous Tokio Runtime",
        severity: "ERROR",
        tag: "rust",
        summary: "std::thread::sleep in async files is an ERROR; in synchronous code it is only a WARNING (non-blocking).",
        rationale: "std::thread::sleep blocks the entire OS worker thread, preventing Tokio from servicing hundreds of concurrent tasks on the same thread. This causes severe latency spikes and server lockups. In SYNCHRONOUS code (CLIs without async runtime), blocking is expected behavior — hence the context-aware rule.",
        bad_example: "async fn handle_request() {\n    std::thread::sleep(Duration::from_millis(500));\n}",
        good_example: "async fn handle_request() {\n    tokio::time::sleep(Duration::from_millis(500)).await;\n}",
        remediation: "In async files, replace with tokio::time::sleep(duration).await. In synchronous CLIs, usage is legitimate and remains a Warning — no stenio-ignore required.",
    },
    RuleExplanation {
        id: "RUST-STRUCTURED-LOGGING",
        name: "Unstructured println!/eprintln! in Web Server",
        severity: "WARN",
        tag: "rust",
        summary: "Prohibits println! in Axum/Tokio services and route handlers.",
        rationale: "Raw println! to stdout loses critical structured metadata (timestamps, spans, trace IDs, log levels, output redirection). Use the tracing macro suite for production observability.",
        bad_example: "println!(\"Request received for {}\", id);",
        good_example: "tracing::info!(user_id = %id, \"Request processed successfully\");",
        remediation: "Replace with tracing::info!, tracing::warn!, tracing::error!, or tracing::debug!.",
    },
    RuleExplanation {
        id: "SEC-SECRETS",
        name: "Hardcoded Secrets & Credentials in Code",
        severity: "ERROR",
        tag: "sec",
        summary: "Detects private keys, GitHub tokens (ghp_), OpenAI keys (sk-), or plaintext passwords.",
        rationale: "Versioned credentials permanently leak into Git history, exposing personal and client infrastructure to automated internet scrapers and credential stuffing.",
        bad_example: "let api_key = \"sk-1234567890abcdef1234567890abcdef12345678\";\nconst GITHUB_TOKEN = \"ghp_abcdef1234567890abcdef123456789012\";",
        good_example: "let api_key = std::env::var(\"OPENAI_API_KEY\")?;\n// Or loaded from SOPS/Age vault in secrets.env",
        remediation: "Remove credential immediately, revoke it with the provider, and inject via environment variables or SOPS/Age vault.",
    },
    RuleExplanation {
        id: "SEC-SQL",
        name: "Insecure String Interpolation in SQL Queries",
        severity: "WARN",
        tag: "sec",
        summary: "Detects raw formatted strings directly inside SQL query definitions.",
        rationale: "Direct string interpolation in SQL opens critical SQL Injection vulnerabilities, exposing databases to data exfiltration or catastrophic deletion.",
        bad_example: "let query = format!(\"SELECT * FROM users WHERE id = {}\", user_id);",
        good_example: "sqlx::query!(\"SELECT * FROM users WHERE id = $1\", user_id).fetch_one(&pool).await?;",
        remediation: "Use bind parameters ($1, $2, ?) in SQLx prepared queries.",
    },
    RuleExplanation {
        id: "SEC-EXCEPT",
        name: "Prohibited Bare Except",
        severity: "WARN",
        tag: "sec",
        summary: "Prohibits 'except:' blocks lacking specific exception types.",
        rationale: "Indiscriminate 'except:' intercepts KeyboardInterrupt, SystemExit, and MemoryErrors, preventing graceful script termination and concealing critical failures.",
        bad_example: "try:\n    do_something()\nexcept:\n    pass",
        good_example: "try:\n    do_something()\nexcept SpecificError as err:\n    logger.error(\"Error: %s\", err)",
        remediation: "Specify the concrete exception class (e.g. 'except Exception as err:' or specific error type).",
    },
    RuleExplanation {
        id: "FRONT-ZUSTAND",
        name: "Unstable Zustand Store Selector",
        severity: "WARN",
        tag: "frontend",
        summary: "Detects new object literals returned in Zustand store selectors without useShallow.",
        rationale: "When a Zustand selector returns an object literal '{ a, b }', a new object reference is allocated on every render cycle, triggering infinite re-renders and freezing the browser.",
        bad_example: "const { activeId, status } = useSessionStore(state => ({ activeId: state.id, status: state.status }));",
        good_example: "import { useShallow } from 'zustand/react/shallow';\nconst { activeId, status } = useSessionStore(\n    useShallow(state => ({ activeId: state.id, status: state.status }))\n);",
        remediation: "Wrap selector with useShallow(...) from 'zustand/react/shallow'.",
    },
    RuleExplanation {
        id: "FRONT-LOGS",
        name: "Residual Frontend Debug Logs",
        severity: "WARN",
        tag: "frontend",
        summary: "Detects console.log and console.debug in React/TypeScript components.",
        rationale: "Debug logs in production pollute browser consoles, risk leaking sensitive payloads, and degrade rendering performance.",
        bad_example: "console.log(\"Data received:\", data);\nconsole.debug(\"Render count\", count);",
        good_example: "// Remove log or guard with development environment flag:\nif (process.env.NODE_ENV === 'development') {\n    console.info(\"Data:\", data);\n}",
        remediation: "Remove debugging statements or use 'stenio --fix' for automated cleanup.",
    },
    RuleExplanation {
        id: "GOV-LEFTOVER-TEST-ARTIFACTS",
        name: "Mandatory Cleanup of Leftover Test Artifacts / Residual Scratch",
        severity: "ERROR",
        tag: "gov",
        summary: "Detects temporary test files, backups, or scratch files left behind by AI agents.",
        rationale: "Rule 3 of AGENTS.md: 'Files and directories created solely for testing/validation MUST be removed at the end of the task, never left in the workspace or system.' AI agents frequently create 'test.py', 'temp.txt', '*.bak', or 'scratch_*' and forget to clean them up, polluting Syncthing and Git history.",
        bad_example: "test.py in vault root\nscripts/temp_output.txt\napp/server/test_debug.rs\nproject/document.md.bak",
        good_example: "Create temporary files strictly inside the agent's authorized persistent scratch directory (<appDataDir>/brain/<id>/scratch/) or delete immediately with std::fs::remove_file before task completion.",
        remediation: "Delete the temporary artifact immediately or relocate to the authorized scratch directory.",
    },
    RuleExplanation {
        id: "VAULT-FRONTMATTER",
        name: "Mandatory YAML Frontmatter in Vault Notes",
        severity: "ERROR",
        tag: "vault",
        summary: "Requires initial YAML frontmatter with tags in all Markdown notes.",
        rationale: "Obsidian and ecosystem indexing scripts depend on the opening YAML block ('---\\ntags: [...]\\n---') for document cataloging, semantic search, and knowledge graph integrity.",
        bad_example: "# My Note\nNote content without metadata.",
        good_example: "---\ntags: [project, sumaanima]\n---\n\n# My Note\nNote content with metadata.",
        remediation: "Add a YAML header delimited by '---' containing the 'tags:' key at the very top of the file.",
    },
    RuleExplanation {
        id: "VAULT-TAG-TAXONOMY",
        name: "Tag Taxonomy Compliance",
        severity: "ERROR",
        tag: "vault",
        summary: "Requires all tags to belong to the canonical taxonomy in governance/_tags.md.",
        rationale: "Arbitrary tag sprawl fragments navigation and breaks graph clustering in Obsidian. Every tag must be approved and cataloged in the official taxonomy.",
        bad_example: "tags: [my-invented-tag, test123]",
        good_example: "tags: [project, infra, homelab, meta, meetings]",
        remediation: "Consult 'governance/_tags.md' and strictly use canonical cataloged tags.",
    },
    RuleExplanation {
        id: "HOMELAB-NAMING",
        name: "Homelab File Naming Convention (Lowercase Kebab-Case)",
        severity: "ERROR",
        tag: "homelab",
        summary: "Requires files in mnemocine/ to use lowercase letters, digits, and hyphens.",
        rationale: "Canonical documentation standard for Mnemocine homelab. UPPERCASE letters and spaces cause sync collisions across case-insensitive file systems via Syncthing.",
        bad_example: "mnemocine/OSS-ACKNOWLEDGMENTS.md\nmnemocine/Server Guide.md",
        good_example: "mnemocine/oss-acknowledgments.md\nmnemocine/server-guide.md",
        remediation: "Rename file using strictly lowercase characters separated by hyphens.",
    },
    RuleExplanation {
        id: "HOMELAB-NFS-SOFT",
        name: "Mandatory Soft NFS Mount",
        severity: "ERROR",
        tag: "homelab",
        summary: "Prohibits 'hard' NFS mount options on network systems without timeout safeguards.",
        rationale: "Hard NFS mounts cause the Linux kernel to permanently freeze I/O processes if the NAS reboots or network drops, necessitating a hard reboot of the host.",
        bad_example: "192.168.1.100:/export /mnt/nfs nfs defaults,hard 0 0",
        good_example: "192.168.1.100:/export /mnt/nfs nfs defaults,soft,timeo=50,retrans=2 0 0",
        remediation: "Replace 'hard' with 'soft,timeo=50,retrans=2' in mount options inside /etc/fstab or systemd mount units.",
    },
    RuleExplanation {
        id: "INFRA-BASH-STRICT",
        name: "Strict Mode in Bash Scripts",
        severity: "ERROR",
        tag: "infra",
        summary: "Requires 'set -euo pipefail' near the beginning of shell scripts.",
        rationale: "Shell scripts that continue running past silent failures or uninitialized variables cause data corruption and unpredictable infrastructure side effects.",
        bad_example: "#!/usr/bin/env bash\ncp /src /dest\nrm -rf /tmp/files",
        good_example: "#!/usr/bin/env bash\nset -euo pipefail\ncp /src /dest\nrm -rf /tmp/files",
        remediation: "Add 'set -euo pipefail' directly below the '#!/usr/bin/env bash' shebang.",
    },
    RuleExplanation {
        id: "AGENT-NO-LAZY-STUB",
        name: "Prohibition of Lazy AI Stubs and Incomplete Placeholders",
        severity: "ERROR",
        tag: "gov",
        summary: "Detects and forbids incomplete placeholders such as '// rest of code', 'todo!()', 'unimplemented!()', or '/* TODO */'.",
        rationale: "Smaller models (7B/14B) and hurried agents frequently suffer from output truncation or laziness, cutting code short with placeholder summaries to reduce effort. This breaks builds, corrupts runtime contracts, and forces human developers to manually fill in missing code.",
        bad_example: "// rest of the code remains the same...\nfn compute_matrix() {\n    todo!(\"implement later\");\n}\nthrow new Error(\"Not implemented\");",
        good_example: "fn compute_matrix() -> Matrix {\n    let data = calculate_initial_values();\n    Matrix::from_data(data)\n}",
        remediation: "Implement functionality end-to-end without relying on stubs or truncation comments.",
    },
    RuleExplanation {
        id: "AGENT-NO-SUPPRESSION-DIRECTIVES",
        name: "Prohibition of Quality Gate and Type Suppression Directives",
        severity: "ERROR",
        tag: "gov",
        summary: "Forbids @ts-ignore, @ts-nocheck, eslint-disable, type: ignore, and stenio-ignore: all.",
        rationale: "When faced with strict TypeScript compilation errors or architectural guardrails, lazy agents attempt to silence linters using suppression directives instead of fixing underlying types or adhering to API contracts. This degrades type safety across the repository and conceals runtime defects.",
        bad_example: "// @ts-ignore\nconst data = response.data;\n\n// stenio-ignore: all\nlet unsafe = dangerous();",
        good_example: "interface CardResponse { data: Card[] }\nconst data: Card[] = (response as CardResponse).data;",
        remediation: "Declare proper types or refactor code to satisfy system contracts without using suppression directives.",
    },
    RuleExplanation {
        id: "AGENT-NO-TAMPERING-VERIFIER",
        name: "Prohibition of Tampering with Verifiers and Git Hooks",
        severity: "ERROR",
        tag: "gov",
        summary: "Forbids git commit --no-verify, disabling pre-commit hooks, or sabotaging auditing scripts.",
        rationale: "When encountering non-trivial defects, dishonest or hurried agents fall into Goodhart's Law / Reward Hacking: instead of solving the root cause, they attempt to bypass verifiers using '--no-verify' or removing audit hooks.",
        bad_example: "git commit -m 'fix' --no-verify\nrm -f .git/hooks/pre-commit",
        good_example: "stenio --gate\ngit commit -m 'fix: implement proper solution'",
        remediation: "Never use '--no-verify'. StenioSentinel is an inviolable gatekeeper. If unable to resolve the issue, escalate to the user with a detailed explanation.",
    },
    RuleExplanation {
        id: "CONF-NO-WEAKEN-STRICT",
        name: "Prohibition of Weakening Compiler Strict Mode",
        severity: "ERROR",
        tag: "gov",
        summary: "Forbids disabling 'strict: false' or 'noImplicitAny: false' in tsconfig.json.",
        rationale: "When an agent fails to resolve strict TypeScript type checking, a common anti-pattern is disabling strict mode in tsconfig.json. This removes type safety project-wide to disguise the model's inability to write valid types.",
        bad_example: "{\n  \"compilerOptions\": {\n    \"strict\": false\n  }\n}",
        good_example: "{\n  \"compilerOptions\": {\n    \"strict\": true\n  }\n}",
        remediation: "Keep '\"strict\": true' and correct type annotations and interfaces across the source code.",
    },
    RuleExplanation {
        id: "ARCH-SCOPE-ISOLATION",
        name: "Monorepo Scope Isolation Violation",
        severity: "ERROR",
        tag: "arch",
        summary: "Forbids modifying business application code and the Stenio governance engine within the same commit or task.",
        rationale: "The monorepo contains both business application code (sumaenimahub/) and the governance arbiter (governance/stenio/). Allowing a single diff to touch both introduces risks of an agent altering validation rules to force approval of broken application code. Separation of concerns and Goodhart's Law mitigation mandate strictly isolating engine updates from product development.",
        bad_example: "git diff HEAD --name-only\nsumaenimahub/SUMAENIMA-HUB/app/frontend-v2/src/App.tsx\ngovernance/stenio/src/engine.rs",
        good_example: "# Task A (Application):\ngit commit -m 'feat: add audio waveform visualizer' sumaenimahub/\n\n# Task B (Governance):\ngit commit -m 'feat: add new lint rule' governance/stenio/",
        remediation: "Isolate responsibilities: revert governance engine changes (governance/stenio) if working on application code, or split into independent commits/PRs.",
    },
    RuleExplanation {
        id: "ARCH-NO-EDIT-MIRROR",
        name: "Prohibited Direct Modification of Automated Backup Mirror",
        severity: "ERROR",
        tag: "arch",
        summary: "Prohibits editing files in automated backup mirror directories (/mnt/BACKUP/configs-homelab, /mnt/BACKUP/agentic-ai-server-psicopompo).",
        rationale: "Backup mirrors are downstream replicas populated via rsync (config-backup) from individual homelab nodes. Editing mirror files directly does not update the runtime containers on the source hosts and is silently overwritten during the next backup run (05:00 BRT). Configuration changes must always be applied on the upstream source host.",
        bad_example: "write_to_file /mnt/BACKUP/configs-homelab/kavure/data/pihole/compose.yml",
        good_example: "ssh kavure 'nano /home/kavure/data/pihole/compose.yml && docker compose up -d'\n# Next, run config-backup or wait for nightly sync.",
        remediation: "Revert edits in the mirror path. Connect to the upstream host via SSH, edit the source configuration file, test in container runtime, and run config-backup.",
    },
    RuleExplanation {
        id: "TEST-NO-SILENT-SKIP",
        name: "Prohibition of Silent Test Skipping or Commenting",
        severity: "ERROR",
        tag: "test",
        summary: "Forbids commenting out assertions, using #[ignore], or test.skip to 'fix' failing test suites.",
        rationale: "When dealing with failing tests, lazy models often cheat by commenting out assertions or adding skip annotations. This creates a false sense of CI greenness while leaving critical regressions in production.",
        bad_example: "// assert_eq!(result, 42); // commented to pass\n#[test]\n#[ignore]\nfn test_payment() { ... }\ntest.skip(\"should authenticate\", () => { ... });",
        good_example: "#[test]\nfn test_payment() {\n    let result = process_payment(amount);\n    assert_eq!(result, PaymentStatus::Success);\n}",
        remediation: "Do not comment out or ignore tests. Identify why the assertion failed and fix the underlying business logic.",
    },
    RuleExplanation {
        id: "CODE-NO-EMPTY-CATCH",
        name: "Prohibition of Empty Catch or Except Blocks",
        severity: "WARN",
        tag: "gov",
        summary: "Forbids try/catch or try/except blocks that swallow errors silently without logging.",
        rationale: "Silently swallowing exceptions creates zombie failures where an application continues executing in a corrupted state without logs or operational telemetry.",
        bad_example: "try {\n    saveData();\n} catch (e) {}\n\ntry:\n    connect_nas()\nexcept:\n    pass",
        good_example: "try {\n    saveData();\n} catch (e) {\n    console.error(\"Failed to save data:\", e);\n    throw e;\n}\n\ntry:\n    connect_nas()\nexcept Exception as err:\n    logger.error(\"NAS connection failed: %s\", err)\n    raise",
        remediation: "Handle the failure, log with tracing/console.error, or propagate the exception using '?' or 'throw/raise'.",
    },
    RuleExplanation {
        id: "FRONT-TOKEN-PALETTE",
        name: "Prohibition of Generic Tailwind Grays",
        severity: "WARN",
        tag: "frontend",
        summary: "Forbids arbitrary gray utility classes like bg-gray-*, bg-zinc-*, bg-slate-* in Sumænimá Hub React components.",
        rationale: "Sumænimá Hub enforces a unified visual identity (Material You + Zinc Deep Dark + Glassmorphism). Arbitrary gray classes break design consistency and theme synchronization.",
        bad_example: "<div className=\"bg-gray-800 text-gray-200 border border-gray-700\">...</div>",
        good_example: "<div className=\"bg-surface-900 text-on-surface border border-outline sm-glass\">...</div>",
        remediation: "Use canonical design tokens: bg-surface-950 (background), bg-surface-900 (cards), bg-surface-800 (hover), text-on-surface (#e4e4e7), border-outline, or .sm-glass.",
    },
    RuleExplanation {
        id: "FRONT-NO-ANY",
        name: "Prohibition of 'any' in TypeScript",
        severity: "WARN",
        tag: "frontend",
        summary: "Forbids 'any' type annotations ('as any', ': any') in frontend .ts and .tsx files.",
        rationale: "Using 'any' disables TypeScript static analysis, hiding contract desynchronization between frontend clients and Axum backend routes.",
        bad_example: "const handleData = (payload: any) => {\n    const user = payload as any;\n};",
        good_example: "import type { UserProfile } from '@/types/user';\nconst handleData = (payload: UserProfile) => {\n    // Strict, type-safe handling\n};",
        remediation: "Import types from src/types/ or run 'stenio --typegen' to generate updated bindings from Rust backend structs.",
    },
    RuleExplanation {
        id: "FRONT-A11Y-BUTTON",
        name: "Interactive Button Accessibility (aria-label)",
        severity: "WARN",
        tag: "frontend",
        summary: "Enforces aria-label or title attributes on icon-only buttons.",
        rationale: "Buttons without accessible names are invisible to assistive technologies (screen readers), violating WCAG 2.1 AA guidelines.",
        bad_example: "<button onClick={onDelete}>\n    <TrashIcon className=\"w-4 h-4\" />\n</button>",
        good_example: "<button onClick={onDelete} aria-label=\"Delete item\">\n    <TrashIcon className=\"w-4 h-4\" />\n</button>",
        remediation: "Add an aria-label=\"...\" or title=\"...\" attribute describing the button's action.",
    },
    RuleExplanation {
        id: "FRONT-AUDIO-WASM",
        name: "AudioWorklet and WebAssembly Sovereignty",
        severity: "ERROR",
        tag: "frontend",
        summary: "Forbids legacy ScriptProcessorNode in audio capture and DSP pipelines.",
        rationale: "ScriptProcessorNode executes on the browser UI main thread, causing frame drops and audio glitches. The Sumænimá audio engine routes DSP through AudioWorkletNode backed by Rust-compiled WebAssembly.",
        bad_example: "const processor = audioCtx.createScriptProcessor(4096, 1, 1);",
        good_example: "const worklet = new AudioWorkletNode(audioCtx, 'audio-recorder-processor');",
        remediation: "Use AudioWorkletNode alongside the wasm-audio WebAssembly engine.",
    },
    RuleExplanation {
        id: "FRONT-COMPONENT-BUDGET",
        name: "Monolithic Component Budget Violation (>400 Lines)",
        severity: "WARN",
        tag: "frontend",
        summary: "Warns when React .tsx components exceed 400 lines of code.",
        rationale: "Massive components are hard to maintain and tempt AI assistants to truncate code with lazy placeholders. Atomic design mandates decomposing large views into focused sub-components.",
        bad_example: "CockpitView.tsx file with 950 lines containing 8 sub-panels and modal states.",
        good_example: "CockpitView.tsx orchestrating sub-components: <CockpitHeader />, <CockpitTimeline />, <CockpitAudioControls />.",
        remediation: "Decompose the component into smaller submodules under src/components/ or features/.",
    },
    RuleExplanation {
        id: "BACKEND-BLOCKING-IO",
        name: "Blocking I/O (std::fs) in Tokio Async Runtime",
        severity: "ERROR",
        tag: "rust",
        summary: "Forbids synchronous std::fs operations inside Axum async request handlers.",
        rationale: "std::fs blocks OS threads, starving Tokio's multi-threaded worker pool. File I/O in async servers must use non-blocking tokio::fs.",
        bad_example: "async fn save_file(data: &[u8]) {\n    std::fs::write(\"path\", data).unwrap();\n}",
        good_example: "async fn save_file(data: &[u8]) -> Result<()> {\n    tokio::fs::write(\"path\", data).await?;\n    Ok(())\n}",
        remediation: "Replace std::fs with tokio::fs and .await, or delegate long-running synchronous calls to tokio::task::spawn_blocking.",
    },
    RuleExplanation {
        id: "BACKEND-NO-PANIC",
        name: "Prohibition of Panic or Assert in Web Server",
        severity: "WARN",
        tag: "rust",
        summary: "Forbids panic!() or assert!() in web server runtime code outside test suites.",
        rationale: "panic! terminates worker threads and can drop concurrent connections. Server errors must be handled gracefully through AppError and HTTP StatusCodes.",
        bad_example: "if user.is_none() {\n    panic!(\"User not found!\");\n}",
        good_example: "let user = user.ok_or_else(|| (StatusCode::NOT_FOUND, \"User not found\"))?;",
        remediation: "Return Result<..., AppError> with appropriate HTTP status codes instead of causing panics.",
    },
    RuleExplanation {
        id: "ARCH-DRY-DUPLICATION",
        name: "Mandatory DRY (Don't Repeat Yourself) Principle",
        severity: "ERROR (logic) / WARN (low-density)",
        tag: "arch",
        summary: "Detects duplicated substantive code blocks. Adaptive severity: a block that is mostly logic is a blocking ERROR; a low logic-density match (mostly declarative lines) is surfaced as a non-blocking WARN. Blocks made only of declarative lines (struct-field initializers / bare field shorthand) are not reported.",
        rationale: "Smaller models often duplicate logic (filters, pagination, data mapping, card layout) across multiple files. This bloats the codebase, causes visual inconsistencies, and creates technical debt. Common logic must be abstracted.",
        bad_example: "// Duplicated in ComponentA.tsx and ComponentB.tsx:\nconst filtered = items.filter(i => i.name.toLowerCase().includes(q.toLowerCase()));\nconst sorted = filtered.sort((a, b) => a.order - b.order);\nconst paginated = sorted.slice(page * 20, (page + 1) * 20);",
        good_example: "// Abstracted into features/common/hooks/useFilteredCollection.ts:\nconst { items: paginated } = useFilteredCollection(rawItems, { query: q, page, pageSize: 20 });",
        remediation: "Extract the duplicate block into a custom hook ('features/<domain>/hooks/'), reusable component, or shared utility function.",
    },
    RuleExplanation {
        id: "PERF-GPU-ZERO-REPAINT",
        name: "Zero-Repaint on GPU Animations and Hover States",
        severity: "WARN",
        tag: "frontend",
        summary: "Forbids transitioning Paint properties (box-shadow, backdrop-filter, bg-color) on 3D/hover containers.",
        rationale: "In Chromium/WebKit browsers, transitioning heavy box-shadows or gaussian blur filters forces CPU/GPU rasterization and layer repaints every frame (dropping to 15-30 FPS in dense grids). Transitioning the opacity of isolated pseudo-elements runs purely on the GPU Compositor thread (0ms paint, locked 60/120 FPS).",
        bad_example: "/* Forces continuous GPU repaints */\n.magic-card-tilt-container {\n    transition: box-shadow 0.3s ease, background-color 0.3s ease;\n}\n.magic-card-tilt-container:hover {\n    box-shadow: 0 0 24px rgba(234, 179, 8, 0.4);\n}",
        good_example: "/* Pure Compositor: Zero Repaint */\n.magic-card-tilt-container::after {\n    content: '';\n    position: absolute;\n    inset: 0;\n    box-shadow: var(--hover-glow);\n    opacity: 0;\n    transition: opacity 0.25s ease;\n    pointer-events: none;\n    transform: translateZ(0);\n}\n.magic-card-tilt-container:hover::after {\n    opacity: 1;\n}",
        remediation: "Transition opacity or transform exclusively on a ::after pseudo-element with transform: translateZ(0).",
    },
    RuleExplanation {
        id: "PERF-NO-LAYOUT-THRASH",
        name: "Prohibition of Layout Thrashing in Event Handlers",
        severity: "WARN",
        tag: "frontend",
        summary: "Forbids un-cached synchronous geometry reads (getBoundingClientRect / offset*) in mouse/scroll listeners.",
        rationale: "Modern gaming mice report coordinates at 500Hz to 1000Hz. Calling getBoundingClientRect() directly inside a mousemove listener forces synchronous style and layout recalculations hundreds of times per second, blocking the UI rendering thread.",
        bad_example: "const handleMouseMove = (e: React.MouseEvent) => {\n    // Forces reflow on every mouse tick!\n    const rect = e.currentTarget.getBoundingClientRect();\n    const x = e.clientX - rect.left;\n    setPos({ x });\n};",
        good_example: "// Cache rect on hover entry or consume coordinates during rAF tick:\nconst handleMouseMove = (e: React.MouseEvent) => {\n    if (!boundsRef.current) {\n        boundsRef.current = el.getBoundingClientRect();\n    }\n    mousePosRef.current = { x: e.clientX, y: e.clientY };\n    startAnimationLoop();\n};",
        remediation: "Cache bounding box dimensions in useRef on onMouseEnter or buffer mouse coordinates to be consumed inside requestAnimationFrame.",
    },
    RuleExplanation {
        id: "PERF-GPU-CONTAINMENT",
        name: "Grid Layout Containment Violation (.card-cell)",
        severity: "WARN",
        tag: "frontend",
        summary: "Requires CSS containment wrapper (.card-cell) when rendering cards in dense catalog or binder loops.",
        rationale: "Dense grids with 60 to 100+ interactive cards require isolated CSS containment. Without it, tilting a single card in 3D or triggering its hover glow invalidates and repaints all 99 adjacent cards on the page.",
        bad_example: "<div className=\"grid grid-cols-4 gap-4\">\n    {cards.map(c => <MagicCard key={c.id} card={c} />)}\n</div>",
        good_example: "<div className=\"grid grid-cols-4 gap-4\">\n    {cards.map(c => (\n        <div key={c.id} className=\"card-cell\">\n            <MagicCard card={c} />\n        </div>\n    ))}\n</div>",
        remediation: "Wrap the MagicCard inside an element with the '.card-cell' class or 'contain: content'.",
    },
    RuleExplanation {
        id: "PERF-GPU-WILL-CHANGE",
        name: "Unrestricted will-change on Inactive Elements",
        severity: "WARN",
        tag: "frontend",
        summary: "Forbids static will-change declarations on dozens of resting elements.",
        rationale: "'will-change: transform' instructs the GPU to allocate a dedicated backing texture. Applying it indiscriminately across 100 idle cards consumes hundreds of megabytes of VRAM and starves the compositor with zero performance benefit.",
        bad_example: ".magic-card {\n    will-change: transform;\n}",
        good_example: ".magic-card:hover {\n    will-change: transform;\n}",
        remediation: "Apply will-change strictly on interactive pseudo-classes (:hover, :focus) or active modifier classes (.is-hovered).",
    },
    RuleExplanation {
        id: "FRONT-MODULAR-HOOKS",
        name: "Direct Network Call Decoupling in Page Views",
        severity: "WARN",
        tag: "frontend",
        summary: "Forbids direct network calls (fetch, axios, ws) at top-level page components (src/pages/*.tsx).",
        rationale: "Pages should remain clean orchestrators under 400 lines. Mixing API calls, mutations, and local state directly in page roots creates fragile components and prevents logic reuse across tabs or modals.",
        bad_example: "// In src/pages/AranduPage.tsx:\nuseEffect(() => {\n    fetch('/api/v1/cards').then(r => r.json()).then(setCards);\n}, []);",
        good_example: "// In src/pages/AranduPage.tsx:\nconst { cards, isLoading } = useAranduCards();",
        remediation: "Extract network calls, loading states, and error handlers into custom hooks under 'src/features/<domain>/hooks/'.",
    },
    RuleExplanation {
        id: "FRONT-FEEDBACK-ON-ERROR",
        name: "Mandatory Visual Feedback on UI Failure",
        severity: "WARN",
        tag: "frontend",
        summary: "Forbids UI catch blocks that only invoke console.error without notifying the user.",
        rationale: "When user actions fail silently, buttons get stuck in spinning states or the screen appears unresponsive. Every UI mutation must trigger an error toast or update visual error state.",
        bad_example: "try {\n    await saveCard(card);\n} catch (err) {\n    console.error(err);\n}",
        good_example: "try {\n    await saveCard(card);\n} catch (err) {\n    toast.error('Failed to save card.');\n    setError(err.message);\n}",
        remediation: "Add 'toast.error(...)' or update component error state to provide immediate feedback to the user.",
    },
    RuleExplanation {
        id: "FRONT-NO-HARDCODED-HOST",
        name: "Prohibition of Hardcoded Localhost in Frontend",
        severity: "ERROR",
        tag: "frontend",
        summary: "Forbids absolute URLs like 'http://localhost' or 'http://127.0.0.1' in React code.",
        rationale: "Hardcoded localhost URLs break when running in production behind Nginx or from external devices on the local mesh, causing fatal CORS errors and connection failures.",
        bad_example: "const API_URL = 'http://localhost:8000/api/v1/cards';",
        good_example: "const API_URL = import.meta.env.VITE_API_URL || '/api/v1/cards';",
        remediation: "Use relative paths (/api/...) or resolve endpoints via the VITE_API_URL environment variable.",
    },
    RuleExplanation {
        id: "DB-IDEMPOTENT-MIGRATION",
        name: "Mandatory Idempotency in SQL Migrations",
        severity: "ERROR",
        tag: "db",
        summary: "Forbids DDL statements (CREATE/DROP TABLE and INDEX) without IF NOT EXISTS or IF EXISTS guards.",
        rationale: "SQLx migrations must be strictly idempotent. If a deployment halts midway or needs a retry, unguarded DDL statements crash fatally with 'relation already exists'.",
        bad_example: "CREATE TABLE users (id UUID PRIMARY KEY);\nDROP INDEX idx_users_email;",
        good_example: "CREATE TABLE IF NOT EXISTS users (id UUID PRIMARY KEY);\nDROP INDEX IF EXISTS idx_users_email;",
        remediation: "Add 'IF NOT EXISTS' to CREATE TABLE/INDEX and 'IF EXISTS' to DROP TABLE/INDEX.",
    },
    RuleExplanation {
        id: "INFRA-TOPOLOGY-COMPLIANCE",
        name: "Compliance with Canonical Mesh Topology",
        severity: "ERROR",
        tag: "infra",
        summary: "Ensures deployments and services target only authorized nodes in the homelab topology.",
        rationale: "Decommissioned or legacy nodes must not receive workloads. Every deployment target must be registered in 'steniocheck.toml [topology.authorized_hub_nodes]'.",
        bad_example: "deploy_target=\"kuaray\" # decommissioned node",
        good_example: "deploy_target=\"kavure\" # canonical active node",
        remediation: "Update scripts to target authorized canonical nodes: kavure (backend/GPU), ybyra (frontend), psicopompo (workstation).",
    },
    RuleExplanation {
        id: "RUST-NO-UNBOUNDED-CHANNEL",
        name: "Prohibition of Unbounded Tokio Channels",
        severity: "ERROR",
        tag: "rust",
        summary: "Forbids 'tokio::sync::mpsc::unbounded_channel()' in asynchronous code.",
        rationale: "Unbounded channels lack backpressure. If message production outpaces consumer throughput, the queue grows indefinitely until the kernel terminates the process via OOM (Out Of Memory).",
        bad_example: "let (tx, rx) = tokio::sync::mpsc::unbounded_channel();",
        good_example: "let (tx, rx) = tokio::sync::mpsc::channel(64); // Finite capacity with backpressure",
        remediation: "Replace with 'mpsc::channel(buffer_size)' with a finite capacity suitable for the workload.",
    },
    RuleExplanation {
        id: "RUST-ASYNC-BLOCKING-CMD",
        name: "Synchronous Process Command in Async Runtime",
        severity: "ERROR",
        tag: "rust",
        summary: "Forbids 'std::process::Command::new' inside Tokio asynchronous server code.",
        rationale: "std::process::Command blocks worker threads in the Tokio thread pool while waiting for subprocess termination, causing latency spikes and freezing concurrent request processing.",
        bad_example: "let out = std::process::Command::new(\"ffmpeg\").arg(\"-i\").output()?;",
        good_example: "let out = tokio::process::Command::new(\"ffmpeg\").arg(\"-i\").output().await?;",
        remediation: "Use 'tokio::process::Command' with '.await' or delegate blocking execution to 'tokio::task::spawn_blocking'.",
    },
    RuleExplanation {
        id: "RUST-NO-SYNC-MUTEX-AWAIT",
        name: "std::sync::Mutex Held Across Tokio Await Points",
        severity: "WARN",
        tag: "rust",
        summary: "Forbids holding a 'std::sync::Mutex' guard across '.await' suspension points.",
        rationale: "Holding a std::sync::Mutex guard across an .await point blocks worker threads if another task attempts to acquire the lock, inducing silent deadlocks and violating compiler Send guarantees.",
        bad_example: "let guard = self.sync_mutex.lock().unwrap();\ndo_async_work().await;\nprintln!(\"{:?}\", *guard);",
        good_example: "// Option 1: Use tokio::sync::Mutex:\nlet guard = self.async_mutex.lock().await;\ndo_async_work().await;\n\n// Option 2: Release lock before await:\nlet val = { self.sync_mutex.lock().unwrap().clone() };\ndo_async_work().await;",
        remediation: "Migrate to 'tokio::sync::Mutex' or ensure the synchronous guard scope drops before calling .await.",
    },
    RuleExplanation {
        id: "RUST-IDIOMATIC-ARC-CLONE",
        name: "Idiomatic Arc Pointer Cloning",
        severity: "WARN",
        tag: "rust",
        summary: "Prefer 'Arc::clone(&ptr)' over 'ptr.clone()'.",
        rationale: "Official Rust community idioms (RFC 258 / Clippy) recommend Arc::clone(&ptr) to make it unambiguously clear to human reviewers and AI agents that this is an O(1) atomic pointer clone rather than an expensive deep copy of underlying data.",
        bad_example: "let state = server_arc.clone();",
        good_example: "let state = Arc::clone(&server_arc);",
        remediation: "Replace 'ptr.clone()' with 'Arc::clone(&ptr)'.",
    },
    RuleExplanation {
        id: "RUST-IDIOMATIC-SLICES",
        name: "Idiomatic Slice Usage (&str and &[T]) in Parameters",
        severity: "WARN",
        tag: "rust",
        summary: "Functions should accept slice references (&str / &[T]) instead of concrete heap collections (&String / &Vec<T>).",
        rationale: "Accepting &String or &Vec<T> forces callers to allocate heap structures, preventing passing static string literals (&'static str), array slices, or substrings without unnecessary heap allocations.",
        bad_example: "fn find_user(name: &String, ids: &Vec<u64>) -> bool { ... }",
        good_example: "fn find_user(name: &str, ids: &[u64]) -> bool { ... }",
        remediation: "Change parameter types from '&String' to '&str' and '&Vec<T>' to '&[T]'.",
    },
    RuleExplanation {
        id: "RUST-SPAWN-ERROR-HANDLING",
        name: "Error Handling and Traceability in tokio::spawn",
        severity: "WARN",
        tag: "rust",
        summary: "Tasks launched with 'tokio::spawn' must capture their JoinHandle or include tracing instrumentation.",
        rationale: "Spawning fire-and-forget tasks without capturing the JoinHandle or adding tracing instrumentation causes panics and errors to be silently dropped without telemetry or logs in production.",
        bad_example: "tokio::spawn(async move {\n    process_background_event().await;\n});",
        good_example: "let _task = tokio::spawn(\n    async move {\n        if let Err(err) = process_background_event().await {\n            tracing::error!(\"Background event failed: {}\", err);\n        }\n    }\n    .instrument(tracing::info_span!(\"background_event_task\")),\n);",
        remediation: "Instrument the task with tracing::info_span! or retain the JoinHandle to inspect completion outcomes.",
    },
    RuleExplanation {
        id: "GOV-NAMING-KEBAB-CASE",
        name: "Folder Naming Convention (kebab-case)",
        severity: "WARN",
        tag: "gov",
        summary: "Directories across the ecosystem and homelab must follow lowercase kebab-case naming.",
        rationale: "As defined in governance/agent-conventions.md, standardized lowercase kebab-case prevents cross-platform case-sensitivity bugs (Linux vs macOS/Windows), simplifies terminal navigation, and maintains uniform structure across the homelab.",
        bad_example: "sumaenimahub/SUMAENIMA-HUB\nsumaenimahub/STIRPS-PETRI\napp/MyFolder",
        good_example: "sumaenimahub/sumaenima-hub\nsumaenimahub/stirps-petri\napp/my-folder",
        remediation: "Rename directories to lowercase using hyphens instead of underscores or uppercase characters (e.g. 'sumaenima-hub', 'stirps-petri').",
    },
    RuleExplanation {
        id: "OPS-STATIC-PARITY",
        name: "Production Frontend Static Parity Drift",
        severity: "WARN",
        tag: "infra",
        summary: "Detects when edge remote nodes (Ybyra/Kavure) serve legacy SPA bundles compared to local build artifacts.",
        rationale: "When the React/Vite frontend builds new features, cache optimizations, or updated API contracts, but static assets have not been synchronized to edge servers (/var/www/sumaenima), clients receive stale bundles. This leads to performance regressions, UI errors, and calls to nonexistent API routes.",
        bad_example: "Compiling new frontend optimizations while leaving edge nodes running an outdated index-DEcIyMkJ.js bundle.",
        good_example: "stenio --deploy front  # Compiles and atomically syncs edge nodes (Ybyra/Kavure) via rsync and reloads Nginx",
        remediation: "Run 'stenio --deploy front' to atomically sync edge nodes (Ybyra/Kavure) and reload Nginx without downtime.",
    },
    RuleExplanation {
        id: "RUST-CANONICAL-REMOTE",
        name: "Raw Remote Command Forbidden (Use crate::remote)",
        severity: "ERROR",
        tag: "rust",
        summary: "Forbids scattered Command::new(\"ssh\") and Command::new(\"rsync\"); mandates crate::remote driver.",
        rationale: "Ad-hoc remote commands without standardized networking flags cause silent freezes when Tailscale SSH requires web re-authentication. The 'crate::remote' driver encapsulates strict timeouts, canonical flags (-o BatchMode=yes), and reauth detection without hanging agents or daemons.",
        bad_example: "let output = Command::new(\"ssh\").arg(\"ybyra\").arg(\"ls\").output();\nlet rsync = Command::new(\"rsync\").args(&[\"-avz\", src, dest]).status();",
        good_example: "let outcome = crate::remote::run_ssh(\"ybyra\", \"ls\", 5);\nlet outcome = crate::remote::run_rsync(src, dest, 10);",
        remediation: "Replace direct Command::new(\"ssh\") or Command::new(\"rsync\") calls with 'crate::remote::run_ssh' or 'crate::remote::run_rsync'.",
    },
    RuleExplanation {
        id: "SEO-INDEX-METADATA",
        name: "Required Document Head SEO Metadata Missing",
        severity: "ERROR",
        tag: "seo",
        summary: "Enforces essential <title>, <meta name=\"description\"> and <link rel=\"canonical\"> tags in index.html.",
        rationale: "Search engine crawlers (Google, Bing, DuckDuckGo) mandate a clear title and description snippet. Missing or malformed head metadata severely hurts SERP click-through rates and causes ranking dilution across duplicate URLs.",
        bad_example: "<!doctype html>\n<html>\n<head>\n  <title></title>\n  <!-- Missing description and canonical tags -->\n</head>",
        good_example: "<head>\n  <title>Sumænimá</title>\n  <meta name=\"description\" content=\"A ponte entre a investigação antropológica, engenharia de dados e design de produto. Soluções tecnológicas soberanas para problemas complexos.\" />\n  <link rel=\"canonical\" href=\"https://sumaenima.chimaera-heptatonic.ts.net/\" />\n</head>",
        remediation: "Add an accurate <title>, a descriptive <meta name=\"description\" content=\"...\"> (120-160 chars), and a canonical <link rel=\"canonical\"> pointing to the primary URL.",
    },
    RuleExplanation {
        id: "SEO-SOCIAL-GRAPH",
        name: "Incomplete Open Graph or Twitter Card Tags",
        severity: "ERROR",
        tag: "seo",
        summary: "Mandates og:title, og:description, og:image, and twitter:card meta tags in web entrypoints.",
        rationale: "Messengers and social platforms (WhatsApp, LinkedIn, Telegram, X) do not execute clientside JavaScript. Without static Open Graph tags in initial HTML, shared links will render as bare plain URLs with no rich preview cards.",
        bad_example: "<!-- No og:* or twitter:* tags declared in index.html -->",
        good_example: "<meta property=\"og:title\" content=\"Sumænimá\" />\n<meta property=\"og:description\" content=\"...\" />\n<meta property=\"og:image\" content=\"https://sumaenima.../og-image.png\" />\n<meta name=\"twitter:card\" content=\"summary_large_image\" />",
        remediation: "Declare complete Open Graph and Twitter Card tags in the <head> of index.html, referencing an optimized 1200x630 banner.",
    },
    RuleExplanation {
        id: "SEO-FAVICON-SPEC",
        name: "Missing 48px Multi-Resolution Favicon Specification",
        severity: "ERROR",
        tag: "seo",
        summary: "Enforces Google Search Central compliance for 48px multiples or multi-layer .ico favicons.",
        rationale: "Googlebot-Image discards SVGs and invalid HTML responses when fetching favicons for SERP display. Google Search requires a multiple of 48px (e.g. 48x48 PNG) or a valid .ico file containing a 48px layer.",
        bad_example: "<link rel=\"icon\" type=\"image/svg+xml\" href=\"/logo.svg\" />\n<!-- Missing /favicon.ico and 48x48 fallback PNG -->",
        good_example: "<link rel=\"icon\" type=\"image/x-icon\" href=\"/favicon.ico\" sizes=\"48x48 32x32 16x16\" />\n<link rel=\"icon\" type=\"image/png\" sizes=\"48x48\" href=\"/favicon-48x48.png\" />",
        remediation: "Generate a multi-layer favicon.ico (16, 32, 48px) and a favicon-48x48.png, placing them in public/ and linking them in index.html.",
    },
    RuleExplanation {
        id: "SEO-SCHEMA-JSONLD",
        name: "Missing Schema.org JSON-LD Structured Data",
        severity: "ERROR",
        tag: "seo",
        summary: "Requires structured Schema.org JSON-LD metadata for brand entity recognition in search engines.",
        rationale: "Search engines construct Knowledge Panels and rich snippets using structured JSON-LD data. Declaring Organization or WebSite schemas gives Google explicit certainty regarding brand identity, founders, and official portals.",
        bad_example: "<!-- No structured data declared in index.html -->",
        good_example: "<script type=\"application/ld+json\">\n{\n  \"@context\": \"https://schema.org\",\n  \"@type\": \"Organization\",\n  \"name\": \"Sumænimá\",\n  \"url\": \"https://...\"\n}\n</script>",
        remediation: "Add a <script type=\"application/ld+json\"> block inside <head> with Organization or WebSite definitions.",
    },
    RuleExplanation {
        id: "SEO-ROBOTS-SITEMAP",
        name: "Web Crawling Assets (robots.txt / sitemap.xml) Missing or Malformed",
        severity: "ERROR",
        tag: "seo",
        summary: "Enforces well-formed robots.txt with User-agent and Sitemap directives, and valid XML sitemaps.",
        rationale: "Crawlers require a valid robots.txt and sitemap.xml to discover, crawl, and schedule deep route indexing without overwhelming server resources or hitting SPA fallback loops.",
        bad_example: "# Empty robots.txt or sitemap.xml returning SPA HTML fallback",
        good_example: "# robots.txt\nUser-agent: *\nAllow: /\nDisallow: /api/\nSitemap: https://sumaenima.../sitemap.xml",
        remediation: "Ensure public/robots.txt defines 'User-agent: *' and points to 'Sitemap: ...', and that sitemap.xml conforms to the sitemaps.org 0.9 XML schema.",
    },
    RuleExplanation {
        id: "SEO-IMG-ALT",
        name: "Image Tag Missing Descriptive Alt Attribute",
        severity: "ERROR",
        tag: "seo",
        summary: "Enforces mandatory descriptive alt attribute (or aria-hidden='true') on all <img> elements.",
        rationale: "Google Search Central relies on image alt text to understand visual content for Google Images ranking and organic search context. Missing alt text also breaks accessibility for assistive technology.",
        bad_example: "<img src=\"/hero.jpg\" />\n<img src=\"/logo.png\" alt=\"\" />  <!-- empty alt without aria-hidden -->",
        good_example: "<img src=\"/hero.jpg\" alt=\"Sumænimá Digital Bureau Hero Banner\" />\n<img src=\"/decor.png\" alt=\"\" aria-hidden=\"true\" />",
        remediation: "Add a descriptive alt=\"...\" attribute or aria-hidden=\"true\" for purely decorative graphics.",
    },
];

pub fn get_explanation(rule_id: &str) -> Option<&'static RuleExplanation> {
    EXPLANATIONS
        .iter()
        .find(|e| e.id.eq_ignore_ascii_case(rule_id))
}

pub fn format_explanation_cli(exp: &RuleExplanation) -> String {
    let sev_badge = if exp.severity == "ERROR" {
        "CRITICAL ERROR".red().bold()
    } else {
        "WARNING".yellow().bold()
    };

    let mut s = String::new();
    s.push_str(&format!(
        "\n{}\n",
        "══════════════════════════════════════════════════════════════════════════════"
            .cyan()
            .bold()
    ));
    s.push_str(&format!(
        "🛡️  StenioSentinel Rule Reference: [{}] {}\n",
        exp.id.green().bold(),
        exp.name.white().bold()
    ));
    s.push_str(&format!(
        "   Severity: {} | Tag: {}\n",
        sev_badge,
        exp.tag.magenta()
    ));
    s.push_str(&format!(
        "{}\n\n",
        "──────────────────────────────────────────────────────────────────────────────".cyan()
    ));

    s.push_str(&format!("📋 {}\n   {}\n\n", "SUMMARY:".bold(), exp.summary));
    s.push_str(&format!(
        "💡 {}\n   {}\n\n",
        "RATIONALE / MOTIVATION:".bold(),
        exp.rationale
    ));

    s.push_str(&format!(
        "❌ {}\n",
        "INCORRECT CODE EXAMPLE (VIOLATION):".red().bold()
    ));
    for line in exp.bad_example.lines() {
        s.push_str(&format!("   {}\n", line.red()));
    }
    s.push('\n');

    s.push_str(&format!(
        "✅ {}\n",
        "COMPLIANT CODE EXAMPLE (CONFORMING):".green().bold()
    ));
    for line in exp.good_example.lines() {
        s.push_str(&format!("   {}\n", line.green()));
    }
    s.push('\n');

    s.push_str(&format!(
        "🔧 {}\n   {}\n\n",
        "REMEDIATION / HOW TO FIX:".cyan().bold(),
        exp.remediation
    ));

    s.push_str(&format!(
        "{}\n",
        "══════════════════════════════════════════════════════════════════════════════"
            .cyan()
            .bold()
    ));

    s
}

pub fn format_explanation_plain(exp: &RuleExplanation) -> String {
    format!(
        "RULE: [{}] {} (Severity: {}, Tag: {})\n\n\
        SUMMARY:\n{}\n\n\
        RATIONALE:\n{}\n\n\
        INCORRECT EXAMPLE (VIOLATION):\n{}\n\n\
        COMPLIANT EXAMPLE (CONFORMING):\n{}\n\n\
        REMEDIATION:\n{}",
        exp.id,
        exp.name,
        exp.severity,
        exp.tag,
        exp.summary,
        exp.rationale,
        exp.bad_example,
        exp.good_example,
        exp.remediation
    )
}

pub fn list_all_explanations() -> String {
    let mut s = String::new();
    s.push_str("\nDocumented Rules in StenioSentinel Reference:\n\n");
    for exp in EXPLANATIONS {
        s.push_str(&format!(
            "  • {:<26} [{:<5}] {:<7} - {}\n",
            exp.id, exp.tag, exp.severity, exp.name
        ));
    }
    s.push_str("\nUse 'stenio --explain <RULE_ID>' for details, violations, and compliant examples.\n");
    s
}
