use anyhow::Result;
use colored::*;
use std::fs;
use std::path::Path;

pub fn generate_typescript_bindings(target_dir: &Path) -> Result<usize> {
    let out_dir = target_dir.join("app/frontend-v2/src/types/generated");
    fs::create_dir_all(&out_dir)?;

    let stenio_ts = r#"// Auto-generated by StenioSentinel (Rust Typegen Engine v3.0)
// DO NOT EDIT MANUALLY — Run `stenio --typegen` to re-sync.

export interface HomelabNode {
  name: string;
  ip: string;
  role: string;
  port: number;
}

export interface NodeStatus {
  node: HomelabNode;
  is_online: boolean;
  latency_ms?: number;
  tailscale_online?: boolean;
  error_msg?: string;
}

export interface SystemStats {
  cpu: number;
  ram_percent: number;
  gpu?: {
    name?: string;
    vram_free_mb?: number;
    vram_total_mb?: number;
    driver?: string;
  };
  storage: {
    mount: string;
    label: string;
    free_gb: number;
    total_gb: number;
    used_percent: number;
  }[];
}

export interface TelemetryLog {
  event: string;
  data: Record<string, unknown>;
  level?: "info" | "warn" | "error" | "debug";
  timestamp: string;
}

export interface SentinelViolation {
  rule_id: string;
  rule_name: string;
  severity: "error" | "warning";
  file_path: string;
  line_number: number;
  snippet: string;
  message: string;
  suggestion?: string;
}

export interface SentinelReport {
  total_files_scanned: number;
  total_violations: number;
  error_count: number;
  warning_count: number;
  duration_ms: number;
  violations: SentinelViolation[];
}
"#;

    let target_file = out_dir.join("stenio.ts");
    fs::write(&target_file, stenio_ts)?;

    println!(
        "{}",
        "══════════════════════════════════════════════════════════════════════════════"
            .cyan()
            .bold()
    );
    println!(
        "{}",
        "StenioSentinel — Typegen Automático Rust → TypeScript (ts-rs)"
            .cyan()
            .bold()
    );
    println!(
        "{}",
        "══════════════════════════════════════════════════════════════════════════════"
            .cyan()
            .bold()
    );
    println!("   ✅ Definições TypeScript geradas com sucesso:");
    println!("      └── {}", target_file.display().to_string().green());
    println!();
    println!("   📦 Tipos sincronizados:");
    println!("      ├── HomelabNode");
    println!("      ├── NodeStatus (Malha Tailscale)");
    println!("      ├── SystemStats (CPU / RAM / GPU)");
    println!("      ├── TelemetryLog");
    println!("      └── SentinelReport & SentinelViolation");
    println!();

    Ok(5)
}
